version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker/node/Dockerfile
    image: backend_http:latest
    command: bash -c "/wait && npm start"
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5762
      WAIT_TIMEOUT: 60
    env_file:
      - .env
    ports:
      - 5003:5000
    depends_on:
      - rabbitmq
      - mongodb
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  mongodb:
    image: mongo:6.0
    volumes:
      - ~/.docker-conf/mongodb/data2/:/data/db