version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker/node/Dockerfile
    image: backend_http:latest
    command: bash -c "/wait && npm start"
    environment:
      WAIT_HOSTS: mongodb:27017
      WAIT_TIMEOUT: 60
    env_file:
      - .env
    ports:
      - 5003:5000
    depends_on:
      - mongodb
#  rabbitmq:
#    image: 'bitnami/rabbitmq:latest'
#    user: "root"
#    ports:
#      - 5672:5672
#      - 15672:15672
  mongodb:
    image: mongo:latest
    volumes:
      - ../mongo_data:/data/db