export enum TaskStateEnum {
    PENDING = "PENDING",
    REJECTED = "REJECTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED"
}

export enum TaskMessageEventType {
    ON_TASK_CREATED = "ON_TASK_CREATED",
    ON_TASK_DELETED = "ON_TASK_DELETED",
    ON_TASK_UPDATED = "ON_TASK_UPDATED",
    ON_TASK_STATE_CHANGED = "ON_TASK_STATE_CHANGED"
}